name: Build Padavan K2P

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          unzip wget git build-essential gawk flex bison \
          gettext libncurses5-dev python3-docutils zlib1g-dev \
          libssl-dev tar curl

    - name: Clone Padavan source code
      run: |
        if [ ! -d /opt/rt-n56u ]; then
          sudo mkdir -p /opt/rt-n56u
          sudo chown $USER:$USER /opt/rt-n56u
          git clone https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        fi

    - name: Download toolchain
      run: |
        cd /opt/rt-n56u/trunk/tools
        mkdir -p go
        # 下载 Go 1.15.2
        if [ ! -f go/go1.15.2.linux-amd64.tar.gz ]; then
          wget -O go/go1.15.2.linux-amd64.tar.gz https://golang.org/dl/go1.15.2.linux-
